name: CI workflow

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.dockerignore'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: 'ubuntu-latest'

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['18.8.0'] 

    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1 
      DATABASE_POSTGRES_URL: "postgres://prisma:prisma@localhost:5432/tests"

    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Run docker/docker-compose.yml
        run: docker-compose -f docker/docker-compose.yml up -d

      - uses: pnpm/action-setup@v2.2.2
        with:
          run_install: false
          version: 7

      - name: User Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Test issue \#8832
        run: |
          pnpx prisma db push
          pnpx test
        working-directory: './packages/issue-8832'
        env:
          DATABASE_URL: ${{ env.DATABASE_POSTGRES_URL }}
